create table address
(
    id       bigint generated by default as identity
        primary key,
    city     varchar(255),
    country  varchar(255),
    state    varchar(255),
    street   varchar(255),
    zip_code varchar(255)
);

alter table address
    owner to postgres;

create table country
(
    id   integer generated by default as identity
        primary key,
    code varchar(255),
    name varchar(255)
);

alter table country
    owner to postgres;

create table customer
(
    id         bigint generated by default as identity
        primary key,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255)
);

alter table customer
    owner to postgres;

create table orders
(
    id                    bigint generated by default as identity
        primary key,
    date_created          timestamp,
    last_updated          timestamp,
    order_tracking_number varchar(255),
    status                varchar(255),
    total_price           numeric(19, 2),
    total_quantity        integer,
    billing_address_id    bigint
        constraint fkqraecqgbbr1p37ic9dr44e2dr
            references address,
    customer_id           bigint
        constraint fk624gtjin3po807j3vix093tlf
            references customer,
    shipping_address_id   bigint
        constraint fkh0uue95ltjysfmkqb5abgk7tj
            references address
);

alter table orders
    owner to postgres;

create table order_item
(
    id         bigint generated by default as identity
        primary key,
    image_url  varchar(255),
    product_id bigint,
    quantity   integer,
    unit_price numeric(19, 2),
    order_id   bigint
        constraint fkt4dc2r9nbvbujrljv3e23iibt
            references orders
);

alter table order_item
    owner to postgres;

create table product_category
(
    id            bigint generated by default as identity
        primary key,
    category_name varchar(255)
);

alter table product_category
    owner to postgres;

create table product
(
    id             bigint generated by default as identity
        primary key,
    active         boolean not null,
    date_created   timestamp,
    description    varchar(255),
    image_url      varchar(255),
    last_updated   timestamp,
    name           varchar(255),
    sku            varchar(255),
    unit_price     numeric(19, 2),
    units_in_stock integer,
    category_id    bigint  not null
        constraint fk5cypb0k23bovo3rn1a5jqs6j4
            references product_category
);

alter table product
    owner to postgres;

create table state
(
    id         integer generated by default as identity
        primary key,
    name       varchar(255),
    country_id integer
        constraint fkghic7mqjt6qb9vq7up7awu0er
            references country
);

alter table state
    owner to postgres;